export {
  coerceRowId,
  deleteCustomerFromSupabase,
  deleteDefectiveEntryFromSupabase,
  deleteExpenseFromSupabase,
  deleteExpenseRecurrenceFromSupabase,
  deletePurchaseFromSupabase,
  deleteProductFamilyFromSupabase,
  deleteProductFromSupabase,
  deleteSaleFromSupabase,
  fetchFullAppDataFromSupabase,
  insertCustomerToSupabase,
  insertDefectiveEntryToSupabase,
  insertExpenseRecurrenceToSupabase,
  insertExpenseToSupabase,
  insertProductFamilyAndProductsToSupabase,
  insertProductFamilyToSupabase,
  insertProductToSupabase,
  insertPurchaseWithOneItemToSupabase,
  insertSaleWithItemsToSupabase,
  patchCustomerInSupabase,
  patchExpenseInSupabase,
  patchExpenseRecurrenceInSupabase,
  patchPurchaseInSupabase,
  patchProductFamilyInSupabase,
  patchProductInSupabase,
  replaceSaleInSupabase,
  requireUuid,
  setProductStockInSupabase,
  upsertSingletonSettingsToSupabase,
  UUID_REGEX,
} from "./app-data-supabase";
export { getSupabaseBrowserClient } from "./client";
export { isSupabaseConfigured } from "./env";
export { pingSupabase } from "./health";
export {
  loadInitialAppData,
  mirrorAfterProductRemovalAsync,
  mirrorCustomerDeleteAsync,
  mirrorCustomerInsertAsync,
  mirrorCustomerPatchAsync,
  mirrorDefectiveDeleteAsync,
  mirrorDefectiveInsertAsync,
  mirrorExpenseAsync,
  mirrorExpenseDeleteAsync,
  mirrorExpensePatchAsync,
  mirrorExpenseRecurrenceDeleteAsync,
  mirrorExpenseRecurrenceInsertAsync,
  mirrorExpenseRecurrencePatchAsync,
  mirrorProductDeleteAsync,
  mirrorProductFamilyDeleteAsync,
  mirrorProductFamilyPatchAsync,
  mirrorProductFamilyWithVariantsAsync,
  mirrorProductInsertAsync,
  mirrorProductPatchAsync,
  mirrorProductStockAsync,
  mirrorPurchaseAsync,
  mirrorPurchaseDeleteAsync,
  mirrorPurchasePatchAsync,
  mirrorSaleAsync,
  mirrorSaleDeleteAsync,
  mirrorSaleReplaceAsync,
  mirrorSettingsAsync,
} from "./mirror-app-data";
